name: CI build wheels

on:
  workflow_dispatch:
  release:
    types:
      - released

jobs:
  build_wheel_and_sdist:
    name: Build pure Python wheel and source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: '3.12'

      - name: Build sdist and wheel
        run: |
          pip install wheel build
          python -m build .

      - name: Test
        run: |
          pip install dist/identifiability*.whl
          python -s -c "import identifiability"

      - uses: actions/upload-artifact@v4
        name: Upload build artifacts
        with:
          name: wheel_and_tarball
          path: dist/*

  upload_pypi:
    needs: build_wheel_and_sdist
    runs-on: ubuntu-latest
    # to publish when a GitHub Release is created:
    if: github.event_name == 'release' && github.event.action == 'released'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: wheel_and_tarball
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
#          repository_url: https://test.pypi.org/legacy/
